included:
  - Sources
  - Tests

excluded:
  - Carthage
  - Pods
  - Generated

opt_in_rules:
  - empty_count
  - force_unwrapping
  - closure_spacing
  - unowned_variable_capture
  - array_init
  - yoda_condition
  - attributes

disabled_rules:
  - line_length # Allow flexibility in some cases
  - identifier_name # Avoid flagging short variables like i/j/x
  - type_name # Some wrappers like `InMemory<String, Preferences>` can be long

reporter: xcode

cyclomatic_complexity:
  warning: 10
  error: 20

function_body_length:
  warning: 40
  error: 80

type_body_length:
  warning: 200
  error: 400

file_length:
  warning: 400
  error: 800

identifier_name:
  excluded:
    - id
    - x
    - y
    - i
    - j
